## numpy.hstack
numpy.hstack(tup, *, dtype=None, casting='same_kind')

-> Stack arrays in sequence horizontally (column wise).

-> This is equivalent to concatenation along the second axis(i.e column number may differ as it stacks along columns which is horizontal), except for 1-D arrays where it concatenates along the first axis. 

-> Rebuilds arrays divided by hsplit.

-> This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-data with a height (first axis), width (second axis), and r/g/b channels (third axis). 

-> The functions concatenate, stack and block provide more general stacking and concatenation operations.

Parameters:

->'tup': sequence of ndarrays
The arrays must have the same shape along all but the second axis, except 1-D arrays which can be any length.

->'dtype': str or dtype(added in version 1.24)
If provided, the destination array will have this dtype. Cannot be provided together with out.

->'casting':{‘no’, ‘equiv’, ‘safe’, ‘same_kind’, ‘unsafe’}, optional(current ver:1.24 may 23)
Controls what kind of data casting may occur. Defaults to ‘same_kind’.

->Returns: 'stackedndarray'
The array formed by stacking the given arrays.


In [1]:
import numpy as np
a = np.array((1,2,3))
b = np.array((4,5,6))
print('using hstack on 1d arays: \n',np.hstack((a,b)))
print()

a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
print('using hstack on 2d arays: \n',np.hstack((a,b)))
print()

a = np.linspace(1,8,num=8,dtype='int64').reshape((2,2,2))
b = np.linspace(10,18,num=8,dtype='int64').reshape((2,2,2))
print('3d arrays: ')
print(a,'\n \n',b)
print()
print('using hstack on 3d arrays: \n',np.hstack((a,b)))

using hstack on 1d arays: 
 [1 2 3 4 5 6]

using hstack on 2d arays: 
 [[1 4]
 [2 5]
 [3 6]]

3d arrays: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
 
 [[[10 11]
  [12 13]]

 [[14 15]
  [16 18]]]

using hstack on 3d arrays: 
 [[[ 1  2]
  [ 3  4]
  [10 11]
  [12 13]]

 [[ 5  6]
  [ 7  8]
  [14 15]
  [16 18]]]


## numpy.vstack
numpy.vstack(tup, *, dtype=None, casting='same_kind')

-> Stack arrays in sequence vertically (row wise).

-> This is equivalent to concatenation along the first axis after 1-D arrays of shape (N,) have been reshaped to (1,N). Rebuilds arrays divided by vsplit.

-> This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-data with a height (first axis), width (second axis), and r/g/b channels (third axis). The functions concatenate, stack and block provide more general stacking and concatenation operations.

*np.row_stack is an alias for vstack. They are the same function.*

*Parameters*:

'tup': sequence of ndarrays
->The arrays must have the same shape along all but the first axis. 1-D arrays must have the same length.

'dtype':str or dtype(versionadded:: 1.24)
->If provided, the destination array will have this dtype. Cannot be provided together with out.


'casting':{‘no’, ‘equiv’, ‘safe’, ‘same_kind’, ‘unsafe’}, optional(versionadded:: 1.24)
-> Controls what kind of data casting may occur. Defaults to ‘same_kind’.


Returns: stackedndarray
The array formed by stacking the given arrays, will be at least 2-D.



In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(f'a={a}\n b={b}\n vstack={np.vstack((a,b))}')
print()

a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
print(f'a={a}\n b={b}\n vstack={np.vstack((a,b))}')


a=[1 2 3]
 b=[4 5 6]
 vstack=[[1 2 3]
 [4 5 6]]

a=[[1]
 [2]
 [3]]
 b=[[4]
 [5]
 [6]]
 vstack=[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


*as we seen aboe np.row-stack() ==  np.vstack() as vstack converts 
1D array of shape (N,) to (1,N)
but np.hstack() doesn't convert 1d array to 2d array.*

so alternative to np.hstack() which converts 1d array to 2d array, we use np.column_stack().

## numpy.column_stack(tup)
-> Stacks 1-D arrays as columns into a 2-D array.

->Take a sequence of 1-D arrays and stack them as columns to make a single 2-D array. 

->2-D arrays are stacked as-is, just like with hstack. 1-D arrays are turned into 2-D columns first.

Parameters:

'tup':sequence of 1-D or 2-D arrays.
->Arrays to stack. All of them must have the same first dimension.

Returns: stacked2-D array
The array formed by stacking the given arrays

In [4]:
import numpy as np
a = np.array((1,2,3))
b = np.array((4,5,6))
print('using column_stack on 1d arays: \n',np.column_stack((a,b)))
print()

a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
print('using column_stack on 2d arays: \n',np.column_stack((a,b)))
print()

a = np.linspace(1,8,num=8,dtype='int64').reshape((2,2,2))
b = np.linspace(10,18,num=4,dtype='int64').reshape((2,1,2))
print('3d arrays: ')
print('a=',a,'\n \n','b=',b)
print()
print('using column_stack on 3d arrays: \n',np.column_stack((a,b)))
#As we can see here the differencce between the np.hstack() and np.column_stack() as it converts 
#the 1d array to the 2d array before stacking.

using column_stack on 1d arays: 
 [[1 4]
 [2 5]
 [3 6]]

using column_stack on 2d arays: 
 [[1 4]
 [2 5]
 [3 6]]

3d arrays: 
a= [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
 
 b= [[[10 12]]

 [[15 18]]]

using column_stack on 3d arrays: 
 [[[ 1  2]
  [ 3  4]
  [10 12]]

 [[ 5  6]
  [ 7  8]
  [15 18]]]


### numpy.hsplit(ary, indices_or_sections)

->Splits an array into multiple sub-arrays horizontally (column-wise).

hsplit is equivalent to split with axis=1, the array is always split along the second axis except for 1-D arrays, where it is split at axis=0.

Parameters:
'ary':ndarray
->Array that is to be divided into sub-arrays.

'indices_or_sections': int or 1-D array
If indices_or_sections is an integer N, then the array will be divided into N equal arrays along axis. If such a split is not possible, an error is raised.

*If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split. For example, [2, 3] would, for axis=0, result in ary[:2] ary[2:3] ary[3:]*

*If an index exceeds the dimension of the array along axis, an empty sub-array is returned correspondingly.*

Returns: sub-arrays which is list of ndarrays
->A list of sub-arrays as views into ary.

Raises: ValueError
If indices_or_sections is given as an integer, but a split does not result in equal division.

In [7]:
x = np.arange(16.0).reshape(4, 4)
print(f'x = {x}')

x = [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
